### ISSUE TITLE
Is this repository more advanced than 1.0.13?

### ISSUE THREAD

**Issue by mayuso** [jfree/jfreechart-fse#41]
I have been using JFreeChart for a couple months now (1.0.9), I have found 1.0.13 and also this github repository.

I found no releases of this code, so I am not sure what I should use, should I stay with 1.0.13? Or is this github version more advanced and worth downloading and compiling?

**Comment by ripdajacker** [comment]
Yes it is more advanced than 1.0.13, and depending on your needs, you may want to upgrade if you need the more cutting edge features. What are you using JFreeChart for? If it's simple cases of visualising some data, then you are probably going to be okay with 1.0.13.

You can grab the 1.0.19 version from Maven central using [this link](https://search.maven.org/#artifactdetails%7Corg.jfree%7Cjfreechart%7C1.0.19%7Cjar).

**Comment by jfree** [comment]
Bear in mind that the JFreeChart 1.0.x source code is still in SVN at SourceForge (although most likely I will migrate the code to GitHub at some point):

http://sourceforge.net/p/jfreechart/code/HEAD/tree/branches/jfreechart-1.0.x-branch/

This repo here is used for working on JFreeChart 2.  It cleans up quite a few things, but isn't yet ready for a stable release.

**Comment by mayuso** [comment]
I use it in my job to visualize data Mainly XY charts. (But also Bar, Pie and Line charts), you know, developers can handle a couple excels, but our commercials and rest of employees prefer charts xD.

I now started an open source project directly related to what I learnt about data mining working there and I thought it was a good time to upgrade the APIs I use.

**Comment by ripdajacker** [comment]
If I were you I would go for the latest stable version 1.0.19.

The api will be mostly compatible with 1.0.13.

**Comment by mayuso** [comment]
Thank you! That´s what I will do :)
